<?php
/**
 * @var $block  MaxMage\InternationalTelephoneInput\Block\PhoneNumber
 */
?>

<script type="application/javascript">
    require([
        'jquery',
        'internationalTelephoneInput'
    ], function ($, internationalTelephoneInput) {

        maxMageTelephoneRenderComplete = function() {

            var elem = $("input[name='telephone']").each(function() {
                internationalTelephoneInput(this, <?php echo $block->phoneConfig(); ?>);
            });

        }
    });
</script>
